spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: subject-service
        uri: lb://subject-service
        predicates:
        - Path=/subject/**
        filters:
        - RewritePath=/subject/(?<path>/?.*), /$\{path}
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/student/**
        filters:
        - RewritePath=/student/(?<path>/?.*), /$\{path}
    
server:
  port: 8072
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     

        
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: always