server:
  port: 8089

api-base-path: /api/v1
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
      
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
    enabled-by-default: true